package:
    name:           hipanel-theme-adminlte
    namespace:      hipanel\themes\adminlte
    title:          AdminLte Theme for HiPanel
    type:           yii2-extension
    keywords:       adminlte, theme, hipanel, plugin
    year:           2014

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
